version: '3.8'
services:
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mart_db
    ports:
      - '5432:5432'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

      #    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
#      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
